<?php

/*
|--------------------------------------------------------------------------
| Demo Content
|--------------------------------------------------------------------------
|
| Static sample content used by the public marketing pages while the rental
| domain is still being designed. Every entry here is a stand-in for a future
| database record — once Vehicle/Booking models exist, the marketing views
| should read from Eloquent instead and this file can be removed.
|
*/

return [

    'vehicles' => [
        [
            'slug' => 'toyota-vios-2022',
            'name' => 'Toyota Vios',
            'year' => 2022,
            'type' => 'Sedan',
            'transmission' => 'Automatic',
            'seats' => 5,
            'fuel' => 'Gasoline',
            'price_per_day' => 1800,
            'rating' => 4.8,
            'trips' => 124,
            'location' => 'Cebu City',
            'image' => null,
            'featured' => true,
            'instant_book' => true,
            'description' => 'A dependable, fuel-sipping sedan that handles city traffic and long provincial drives equally well. Recently serviced, spotless interior, and easy to park.',
            'features' => ['Air conditioning', 'Bluetooth audio', 'Dashcam', 'GPS tracker', 'USB charging', 'Reverse camera'],
            'owner' => ['name' => 'Marco Villanueva', 'verified' => true, 'response_time' => '~15 min', 'joined' => 2023, 'trips' => 210],
        ],
        [
            'slug' => 'toyota-fortuner-2023',
            'name' => 'Toyota Fortuner',
            'year' => 2023,
            'type' => 'SUV',
            'transmission' => 'Automatic',
            'seats' => 7,
            'fuel' => 'Diesel',
            'price_per_day' => 4200,
            'rating' => 4.9,
            'trips' => 87,
            'location' => 'Cebu City',
            'image' => null,
            'featured' => true,
            'instant_book' => true,
            'description' => 'Seven-seat SUV with the ground clearance for mountain roads and the cabin space for a full family trip. A favourite for out-of-town weekends.',
            'features' => ['Air conditioning', '7 seats', 'Apple CarPlay', 'GPS tracker', 'Roof rack', 'Cruise control'],
            'owner' => ['name' => 'Rhea Salazar', 'verified' => true, 'response_time' => '~10 min', 'joined' => 2022, 'trips' => 340],
        ],
        [
            'slug' => 'honda-civic-2021',
            'name' => 'Honda Civic',
            'year' => 2021,
            'type' => 'Sedan',
            'transmission' => 'Automatic',
            'seats' => 5,
            'fuel' => 'Gasoline',
            'price_per_day' => 2500,
            'rating' => 4.7,
            'trips' => 96,
            'location' => 'Mandaue City',
            'image' => null,
            'featured' => true,
            'instant_book' => false,
            'description' => 'Sharp handling and a quiet cabin make this a comfortable pick for business trips and airport runs. Turbocharged and surprisingly economical.',
            'features' => ['Air conditioning', 'Bluetooth audio', 'Push start', 'GPS tracker', 'Lane assist', 'Leather seats'],
            'owner' => ['name' => 'Jomar Ancheta', 'verified' => true, 'response_time' => '~30 min', 'joined' => 2023, 'trips' => 118],
        ],
        [
            'slug' => 'mitsubishi-montero-2022',
            'name' => 'Mitsubishi Montero Sport',
            'year' => 2022,
            'type' => 'SUV',
            'transmission' => 'Automatic',
            'seats' => 7,
            'fuel' => 'Diesel',
            'price_per_day' => 3900,
            'rating' => 4.8,
            'trips' => 73,
            'location' => 'Lapu-Lapu City',
            'image' => null,
            'featured' => true,
            'instant_book' => true,
            'description' => 'Powerful diesel SUV with plenty of luggage room. Ideal for beach trips, group travel, and anything involving rough barangay roads.',
            'features' => ['Air conditioning', '7 seats', 'Rear entertainment', 'GPS tracker', 'Tow hitch', '360 camera'],
            'owner' => ['name' => 'Christian Neri', 'verified' => true, 'response_time' => '~20 min', 'joined' => 2021, 'trips' => 402],
        ],
        [
            'slug' => 'toyota-hiace-2021',
            'name' => 'Toyota Hiace Commuter',
            'year' => 2021,
            'type' => 'Van',
            'transmission' => 'Manual',
            'seats' => 15,
            'fuel' => 'Diesel',
            'price_per_day' => 6500,
            'rating' => 4.6,
            'trips' => 58,
            'location' => 'Cebu City',
            'image' => null,
            'featured' => true,
            'instant_book' => false,
            'description' => 'Fifteen-seater van built for group tours, company outings, and airport transfers. Driver service available on request.',
            'features' => ['Air conditioning', '15 seats', 'Large luggage bay', 'GPS tracker', 'PA system', 'Curtains'],
            'owner' => ['name' => 'Hannah Claire Pontillas', 'verified' => true, 'response_time' => '~45 min', 'joined' => 2022, 'trips' => 156],
        ],
        [
            'slug' => 'ford-ranger-2023',
            'name' => 'Ford Ranger',
            'year' => 2023,
            'type' => 'Pickup',
            'transmission' => 'Automatic',
            'seats' => 5,
            'fuel' => 'Diesel',
            'price_per_day' => 4500,
            'rating' => 4.9,
            'trips' => 41,
            'location' => 'Talisay City',
            'image' => null,
            'featured' => true,
            'instant_book' => true,
            'description' => 'Modern pickup with a comfortable cabin and a bed that swallows anything you throw at it. Equally at home hauling cargo or heading up to the highlands.',
            'features' => ['Air conditioning', '4x4', 'Bed liner', 'GPS tracker', 'Apple CarPlay', 'Tow package'],
            'owner' => ['name' => 'Dennis Abadiano', 'verified' => true, 'response_time' => '~25 min', 'joined' => 2023, 'trips' => 64],
        ],
        [
            'slug' => 'suzuki-swift-2020',
            'name' => 'Suzuki Swift',
            'year' => 2020,
            'type' => 'Hatchback',
            'transmission' => 'Automatic',
            'seats' => 5,
            'fuel' => 'Gasoline',
            'price_per_day' => 1200,
            'rating' => 4.5,
            'trips' => 189,
            'location' => 'Mandaue City',
            'image' => null,
            'featured' => false,
            'instant_book' => true,
            'description' => 'The cheapest way to get around the city on four wheels. Tiny turning radius, great mileage, and easy to slot into any parking space.',
            'features' => ['Air conditioning', 'Bluetooth audio', 'GPS tracker', 'USB charging'],
            'owner' => ['name' => 'Kaye Lim', 'verified' => true, 'response_time' => '~1 hr', 'joined' => 2024, 'trips' => 38],
        ],
        [
            'slug' => 'nissan-navara-2022',
            'name' => 'Nissan Navara',
            'year' => 2022,
            'type' => 'Pickup',
            'transmission' => 'Manual',
            'seats' => 5,
            'fuel' => 'Diesel',
            'price_per_day' => 3800,
            'rating' => 4.6,
            'trips' => 52,
            'location' => 'Consolacion',
            'image' => null,
            'featured' => false,
            'instant_book' => false,
            'description' => 'Workhorse pickup for hauling and site visits. Manual transmission, tough suspension, and a bed that has seen real use.',
            'features' => ['Air conditioning', '4x2', 'Bed liner', 'GPS tracker', 'Tow hitch'],
            'owner' => ['name' => 'Arnel Bacus', 'verified' => false, 'response_time' => '~2 hrs', 'joined' => 2024, 'trips' => 19],
        ],
        [
            'slug' => 'toyota-innova-2021',
            'name' => 'Toyota Innova',
            'year' => 2021,
            'type' => 'Van',
            'transmission' => 'Automatic',
            'seats' => 8,
            'fuel' => 'Diesel',
            'price_per_day' => 3200,
            'rating' => 4.7,
            'trips' => 143,
            'location' => 'Cebu City',
            'image' => null,
            'featured' => false,
            'instant_book' => true,
            'description' => 'The family MPV that never quits. Eight seats, generous headroom, and low running costs for longer provincial routes.',
            'features' => ['Air conditioning', '8 seats', 'Bluetooth audio', 'GPS tracker', 'Reverse camera'],
            'owner' => ['name' => 'Grace Tabotabo', 'verified' => true, 'response_time' => '~20 min', 'joined' => 2022, 'trips' => 267],
        ],
        [
            'slug' => 'honda-brv-2023',
            'name' => 'Honda BR-V',
            'year' => 2023,
            'type' => 'SUV',
            'transmission' => 'Automatic',
            'seats' => 7,
            'fuel' => 'Gasoline',
            'price_per_day' => 2900,
            'rating' => 4.8,
            'trips' => 61,
            'location' => 'Lapu-Lapu City',
            'image' => null,
            'featured' => false,
            'instant_book' => true,
            'description' => 'Compact seven-seater that drives like a small car but carries like an SUV. A smart middle ground for larger groups on a budget.',
            'features' => ['Air conditioning', '7 seats', 'Apple CarPlay', 'GPS tracker', 'Push start', 'Cruise control'],
            'owner' => ['name' => 'Rhea Salazar', 'verified' => true, 'response_time' => '~10 min', 'joined' => 2022, 'trips' => 340],
        ],
        [
            'slug' => 'mazda-3-2022',
            'name' => 'Mazda 3',
            'year' => 2022,
            'type' => 'Hatchback',
            'transmission' => 'Automatic',
            'seats' => 5,
            'fuel' => 'Gasoline',
            'price_per_day' => 2700,
            'rating' => 4.9,
            'trips' => 47,
            'location' => 'Cebu City',
            'image' => null,
            'featured' => false,
            'instant_book' => false,
            'description' => 'Easily the nicest interior in this price range. A genuinely enjoyable drive for anyone who cares how a car feels on a winding road.',
            'features' => ['Air conditioning', 'Leather seats', 'Bose audio', 'GPS tracker', 'Head-up display', 'Lane assist'],
            'owner' => ['name' => 'Jomar Ancheta', 'verified' => true, 'response_time' => '~30 min', 'joined' => 2023, 'trips' => 118],
        ],
        [
            'slug' => 'toyota-wigo-2023',
            'name' => 'Toyota Wigo',
            'year' => 2023,
            'type' => 'Hatchback',
            'transmission' => 'Manual',
            'seats' => 5,
            'fuel' => 'Gasoline',
            'price_per_day' => 1400,
            'rating' => 4.4,
            'trips' => 112,
            'location' => 'Talisay City',
            'image' => null,
            'featured' => false,
            'instant_book' => true,
            'description' => 'Small, cheap, and honest. Perfect for solo renters and short city errands where fuel economy matters more than anything else.',
            'features' => ['Air conditioning', 'Bluetooth audio', 'GPS tracker'],
            'owner' => ['name' => 'Kaye Lim', 'verified' => true, 'response_time' => '~1 hr', 'joined' => 2024, 'trips' => 38],
        ],
    ],

    'testimonials' => [
        [
            'quote' => 'I booked a Fortuner for a weekend in Moalboal and the whole thing took four minutes. The ID check was done before I even finished packing.',
            'name' => 'Patricia Gonzales',
            'role' => 'Renter, Cebu City',
            'rating' => 5,
        ],
        [
            'quote' => 'My Innova used to sit idle five days a week. CarHub suggested a price I would never have picked myself and it has been booked almost every weekend since.',
            'name' => 'Grace Tabotabo',
            'role' => 'Vehicle owner',
            'rating' => 5,
        ],
        [
            'quote' => 'Being able to see the exact vehicle on a map before booking removed all the guesswork. No more meeting a stranger in a mall parking lot hoping for the best.',
            'name' => 'Dennis Abadiano',
            'role' => 'Renter, Talisay City',
            'rating' => 5,
        ],
    ],

    'faqs' => [
        [
            'category' => 'Booking',
            'items' => [
                [
                    'question' => 'What do I need to book a vehicle?',
                    'answer' => 'You need to be at least 21 years old, hold a valid driver\'s license, and upload two valid government-issued IDs. Verification is usually completed within a few minutes and only has to be done once.',
                ],
                [
                    'question' => 'Why do you require two valid IDs?',
                    'answer' => 'Two independent IDs let us confirm that you are who you say you are before a stranger\'s vehicle is handed over to you. It protects owners from fraud and gives renters confidence that everyone on the platform has been through the same check.',
                ],
                [
                    'question' => 'How far in advance can I book?',
                    'answer' => 'Up to 90 days ahead. Bookings must start at least two hours from now, run for a minimum of one day, and cannot overlap with an existing reservation on the same vehicle — the calendar enforces all of this before you reach payment.',
                ],
                [
                    'question' => 'Can I extend a rental that is already running?',
                    'answer' => 'Yes, as long as the vehicle has no booking immediately after yours. Request the extension from your trip page and the additional days are charged at the same daily rate.',
                ],
            ],
        ],
        [
            'category' => 'Payments',
            'items' => [
                [
                    'question' => 'Which payment methods do you accept?',
                    'answer' => 'GCash, Maya, major credit and debit cards, and direct bank transfer. Every payment is validated and confirmed before the booking is finalised — a reservation is never held on an unverified payment.',
                ],
                [
                    'question' => 'When am I charged?',
                    'answer' => 'The full rental amount is authorised when you confirm the booking and captured once the owner accepts. If the owner declines or does not respond within the response window, the authorisation is released in full.',
                ],
                [
                    'question' => 'Is there a security deposit?',
                    'answer' => 'Most owners require a refundable deposit, shown on the vehicle page before you book. It is released within three business days of the vehicle being returned in its original condition.',
                ],
                [
                    'question' => 'What is your cancellation policy?',
                    'answer' => 'Free cancellation up to 24 hours before pickup. Inside 24 hours, the first day of the rental is non-refundable. Owner cancellations are always refunded in full.',
                ],
            ],
        ],
        [
            'category' => 'Safety & tracking',
            'items' => [
                [
                    'question' => 'Are the vehicles tracked?',
                    'answer' => 'Yes. Every listed vehicle carries a GPS unit. Owners can see the vehicle\'s location for the duration of an active rental only, and tracking is disabled the moment a trip ends. Renters are told about this before booking and again at pickup.',
                ],
                [
                    'question' => 'Are rentals insured?',
                    'answer' => 'Every trip includes third-party liability coverage. Comprehensive coverage is available as an add-on at checkout and is strongly recommended for longer trips.',
                ],
                [
                    'question' => 'What happens if the vehicle breaks down?',
                    'answer' => 'Roadside assistance is included on every booking. Report the issue from your trip page and we coordinate with the owner — you are not charged for days lost to a mechanical fault.',
                ],
            ],
        ],
        [
            'category' => 'For owners',
            'items' => [
                [
                    'question' => 'How much can I earn?',
                    'answer' => 'It depends on the vehicle and how often you make it available. Our pricing model reads local demand, season, and what comparable vehicles nearby are charging, then suggests a daily rate — you are always free to override it.',
                ],
                [
                    'question' => 'How do I get paid?',
                    'answer' => 'Payouts are released to your GCash, Maya, or bank account within 24 hours of a trip completing. CarHub takes a 15% service fee, which covers payment processing, insurance, and support.',
                ],
                [
                    'question' => 'Can I choose who rents my vehicle?',
                    'answer' => 'Yes. You can require manual approval on every request and review the renter\'s verification status, rating, and trip history before accepting. Instant Book is optional and off by default.',
                ],
            ],
        ],
    ],

];
